/**
 * A stand-in for the surface realm, so the player subsystem can be developed,
 * unit-tested and reasoned about without a planet attached.
 *
 * The real surface realm is generated by another system; all this file promises
 * is the five members of the dependency contract:
 *
 *     sampleHeight(x, z) -> number
 *     sampleNormal(x, z) -> THREE.Vector3
 *     gravity            -> m/s^2
 *     up(worldPos)       -> THREE.Vector3
 *     sunDirection       -> THREE.Vector3
 *
 * Everything the player code uses beyond those five is feature-detected with
 * `world.foo?.()`, so a world that only implements the contract still works.
 * The optional extras are declared here as documentation of what the player will
 * happily consume if the real realm chooses to offer it:
 *
 *     surfaceAt(x, z)    -> { material, friction, dust, colour }
 *     raycast(o, d, max) -> { distance, point, normal } | null
 *
 * Two flavours are provided. `createFlatWorld` is a featureless plane, which is
 * the right thing for asserting analytic results (a jump on a plane has a
 * closed-form apex). `createTestWorld` adds hills, a vertical step and a ramp
 * that is deliberately steeper than any sane slope limit, which is the right
 * thing for asserting that the motor steps up, slides off, and never tunnels.
 */

import * as THREE from 'three';
import { Noise } from '../core/Noise.js';
import { clamp } from '../core/Noise.js';

const _up = new THREE.Vector3(0, 1, 0);
const _n = new THREE.Vector3();

/** A featureless plane at y = 0. Analytic, so tests can assert exact numbers. */
export function createFlatWorld(opts = {}) {
  const gravity = opts.gravity ?? 9.81;
  const height = opts.height ?? 0;
  return {
    kind: 'flat',
    gravity,
    sunDirection: new THREE.Vector3(0.4, 0.72, 0.56).normalize(),
    sampleHeight() {
      return height;
    },
    sampleNormal() {
      return _n.set(0, 1, 0);
    },
    up() {
      return _up;
    },
    surfaceAt() {
      return FLAT_SURFACE;
    },
  };
}

const FLAT_SURFACE = { material: 'regolith', friction: 1, dust: 0.6, colour: 0x9a8f7e };

/**
 * A small terrain with the four features the motor has to survive:
 *   - rolling hills, so ground-following and step phase get exercised
 *   - a 0.4 m ledge, which must be stepped over rather than blocking
 *   - a 2.5 m wall, which must block rather than being climbed
 *   - a 62-degree ramp, which is above any reasonable slope limit and must slide
 *
 * `radius` optionally curves the world into a sphere, which is how the surface
 * realm actually behaves; the player code only ever asks for `up(pos)` so a
 * large radius here is enough to prove the surface-aligned path is exercised.
 */
export function createTestWorld(opts = {}) {
  const gravity = opts.gravity ?? 9.81;
  const seed = opts.seed ?? 7717;
  const radius = opts.radius ?? 0; // 0 = flat/infinite plane
  const noise = new Noise(seed);
  const amp = opts.amplitude ?? 6;

  function terrain(x, z) {
    // Broad rolling hills. Low frequency so a 7 m/s sprint takes a few seconds
    // to cross one, which is roughly the scale at which slopes read as terrain
    // rather than as bumps.
    let h = noise.fbm(x * 0.011, 0, z * 0.011, 4) * amp;

    // A clean vertical wall at x = 40, 2.5 m tall: taller than any step height,
    // so it must be treated as geometry to slide along.
    if (x > 40 && x < 60) h += 2.5;

    // A 0.4 m ledge at z = 30: under the step height, so it must be walked over
    // without the player stopping dead.
    if (z > 30 && z < 46) h += 0.4;

    // A ramp climbing 1.9 m per metre (~62 degrees) between x = -60 and -40.
    if (x < -40) h += clamp((-40 - x) * 1.9, 0, 38);

    return h;
  }

  const world = {
    kind: 'test',
    gravity,
    radius,
    sunDirection: new THREE.Vector3(0.4, 0.72, 0.56).normalize(),
    sampleHeight: terrain,
    sampleNormal(x, z) {
      // Central differences. The epsilon is a compromise: too small and the
      // vertical wall produces a degenerate normal, too large and the ledge
      // smears into a ramp the motor would happily walk up.
      const e = 0.25;
      const hx = terrain(x + e, z) - terrain(x - e, z);
      const hz = terrain(x, z + e) - terrain(x, z - e);
      return _n.set(-hx, 2 * e, -hz).normalize();
    },
    up(pos) {
      if (!radius) return _up;
      // Planet-radial up, with the sphere centred below the origin so that
      // (0, 0, 0) sits on the surface and the flat-world case is the limit.
      return _n
        .set(pos.x, pos.y + radius, pos.z)
        .normalize();
    },
    surfaceAt(x, z) {
      const h = terrain(x, z);
      if (h > amp * 0.55) return SURFACES.rock;
      if (h < -amp * 0.4) return SURFACES.sand;
      return SURFACES.regolith;
    },
  };
  return world;
}

export const SURFACES = {
  regolith: { material: 'regolith', friction: 1.0, dust: 0.7, colour: 0x9a8f7e },
  rock: { material: 'rock', friction: 1.05, dust: 0.25, colour: 0x76736e },
  sand: { material: 'sand', friction: 0.86, dust: 1.0, colour: 0xc2a878 },
  ice: { material: 'ice', friction: 0.16, dust: 0.1, colour: 0xbfe3ef },
  metal: { material: 'metal', friction: 1.1, dust: 0.05, colour: 0x8f97a3 },
  snow: { material: 'snow', friction: 0.72, dust: 0.9, colour: 0xe8f0f6 },
  grass: { material: 'grass', friction: 0.98, dust: 0.35, colour: 0x63805a },
};
