/**
 * The ground, at every distance at once.
 *
 * A planet you can stand on has to be two contradictory things: a thirty-metre
 * patch under your boots resolved to the centimetre, and a horizon eighty
 * kilometres away. The ratio is about six orders of magnitude, and no single
 * mesh spans it. So the visible region is a quadtree over the landing site's
 * tangent plane, subdivided toward the camera, and every leaf is generated by
 * `terrain.worker.js` from the *same* `TerrainField` the character motor asks
 * for `sampleHeight`. There is deliberately no cheaper approximation of the
 * ground anywhere in this file — a mesh that disagrees with collision by a few
 * centimetres reads instantly as sinking or hovering.
 *
 * Three things here are less obvious than they look.
 *
 *   **The tree is planar, not a cube-sphere.** `LocalFrame.directionAt(x, z)`
 *   maps a tangent-plane coordinate onto the globe, and the worker's
 *   `y = -R + sqrt(R^2 + 2Rh + h^2 - x^2 - z^2)` term drops the plane away with
 *   real curvature. Within the few hundred kilometres you can see from a
 *   surface, that is exact to the width of the horizon haze, and it buys a tree
 *   with one root and no seam handling at all. Leaving the neighbourhood of the
 *   site means rebuilding the frame, which is a realm-level concern, not this
 *   file's.
 *
 *   **No per-node uniforms.** A node's level rides in `aMorph.w` and its centre
 *   is the mesh's own model matrix, so every chunk in the scene shares one
 *   material and one program. The alternative — cloning a material per node —
 *   works and is what most implementations do, and it means a few hundred
 *   uniform blocks doing nothing but restating what the transform already says.
 *
 *   **Skirts AND morph.** The morph collapses a node exactly onto its parent's
 *   surface before the swap, which in principle makes cracks impossible. In
 *   practice a node whose neighbour is two levels coarser — which happens for a
 *   frame or two whenever the camera moves fast — still opens a seam, and a
 *   one-pixel crack to the sky is far more visible than a skirt you never
 *   notice. The worker hangs the curtain; this file just draws it.
 */

import * as THREE from 'three';
import { biomeProfile, layerUniformArrays } from './Biomes.js';

// Vertices along one edge of a leaf's visible lattice. The worker pads this by
// one ring on each side for the skirt, so the real grid is (RES + 2)^2.
const RES = 33;

const TERRAIN_VERT = /* glsl */ `
precision highp float;

uniform vec3  uCamLocal;
uniform float uRootSize;
uniform float uSplit;

attribute vec4 aMorph;
attribute vec4 aTerra;

varying vec3 vNormal;
varying vec4 vTerra;
varying vec3 vLocal;
varying float vDist;

void main(){
  // Node size is implied by its level, so it does not need to be uploaded.
  float size = uRootSize / exp2(aMorph.w);

  vec3 wp0 = (modelMatrix * vec4(position, 1.0)).xyz;
  float d = distance(wp0, uCamLocal);

  // A node is on screen between its own split radius and its parent's, i.e.
  // over a factor of two in distance. Morphing across the top half of that band
  // means the geometry is already identical to the parent's by the time the
  // swap happens, so the swap itself is invisible.
  float a = size * uSplit * 1.35;
  float b = size * uSplit * 1.90;
  float t = clamp((d - a) / max(b - a, 1e-3), 0.0, 1.0);

  vec3 p = position + aMorph.xyz * t;
  vec4 wp = modelMatrix * vec4(p, 1.0);

  vLocal  = wp.xyz;
  vNormal = normalize(mat3(modelMatrix) * normal);
  vTerra  = aTerra;
  vDist   = distance(wp.xyz, uCamLocal);

  gl_Position = projectionMatrix * viewMatrix * wp;
}
`;

const TERRAIN_FRAG = /* glsl */ `
precision highp float;

uniform vec3  uLayerColor[4];
uniform vec3  uLayerEmissive[4];
uniform vec4  uRough;
uniform float uFreeze;
uniform float uBeachBand;
uniform float uSnowFactor;
uniform float uMaxElev;
uniform vec3  uSunDir;
uniform vec3  uSunColor;
uniform vec3  uSkyColor;
uniform vec3  uGroundColor;
uniform vec3  uUpLocal;
uniform float uFogDensity;
uniform vec3  uFogColor;

varying vec3 vNormal;
varying vec4 vTerra;
varying vec3 vLocal;
varying float vDist;

// Mirror of biomeProfile().classify in Biomes.js, expression for expression.
//
// The CPU copy decides what a footstep sounds like and what colour the dust is;
// this one decides what the ground looks like. They have to agree, or the
// player walks onto visible snow and hears gravel. Any edit here needs the same
// edit there.
void classify(out vec4 w, float h, float slope, float moisture, float temperature, float flow){
  float relief = clamp(h / max(uMaxElev, 1.0), -1.5, 1.5);

  float cliff =
    smoothstep(0.30, 0.72, slope) * 0.92 +
    smoothstep(0.55, 0.95, relief) * 0.25 +
    smoothstep(0.12, 0.45, slope) * 0.18;

  float cold = smoothstep(uFreeze + 6.0, uFreeze - 8.0, temperature);
  float cap = cold * (1.0 - smoothstep(0.42, 0.78, slope)) * uSnowFactor;

  float wet = clamp(moisture, 0.0, 1.0);
  float ground = (0.35 + 0.65 * wet) * (1.0 - smoothstep(0.30, 0.66, slope));
  float accent = (0.75 - 0.6 * wet) * (1.0 - smoothstep(0.38, 0.80, slope));

  if (flow > 0.02){
    ground += flow * 0.75;
    accent += flow * 0.25;
  }

  if (h < uBeachBand && h > -uBeachBand * 2.5){
    float b = 1.0 - smoothstep(0.0, uBeachBand, max(h, 0.0));
    accent += b * 1.4;
    ground *= 1.0 - b * 0.85;
  }

  w = max(vec4(cliff, ground, accent, cap), vec4(0.0));
  w /= (w.x + w.y + w.z + w.w + 1e-5);
}

void main(){
  vec3 N = normalize(vNormal);
  float slope = clamp(1.0 - dot(N, normalize(uUpLocal)), 0.0, 1.0);

  vec4 w;
  classify(w, vTerra.w, slope, vTerra.x, vTerra.y, vTerra.z);

  vec3 albedo = uLayerColor[0] * w.x + uLayerColor[1] * w.y
              + uLayerColor[2] * w.z + uLayerColor[3] * w.w;
  vec3 emis   = uLayerEmissive[0] * w.x + uLayerEmissive[1] * w.y
              + uLayerEmissive[2] * w.z + uLayerEmissive[3] * w.w;

  // Direct sun with a wrap term. A hard N.L terminator on ground is the same
  // defect the rubric fails planets for: real regolith scatters forward enough
  // that the last few degrees before shadow are a gradient, not an edge.
  float ndl = dot(N, uSunDir);
  float direct = clamp((ndl + 0.18) / 1.18, 0.0, 1.0);

  // Hemispheric ambient: sky above, bounce off the ground below. On an airless
  // world uSkyColor is nearly black and shadows go correctly hard.
  float hemi = dot(N, normalize(uUpLocal)) * 0.5 + 0.5;
  vec3 ambient = mix(uGroundColor, uSkyColor, hemi);

  vec3 col = albedo * (uSunColor * direct + ambient) + emis;

  // Exponential-squared distance haze. Depth cue first, atmosphere second —
  // without it the horizon reads as a cardboard cutout at any view distance.
  float f = 1.0 - exp(-pow(vDist * uFogDensity, 2.0));
  col = mix(col, uFogColor, clamp(f, 0.0, 1.0));

  gl_FragColor = vec4(col, 1.0);
}
`;

/** Triangulation for one padded leaf. Topology is identical for every node. */
function buildIndex(n) {
  const quads = (n - 1) * (n - 1);
  const idx = quads * 6 > 65535
    ? new Uint32Array(quads * 6)
    : new Uint16Array(quads * 6);
  let o = 0;
  for (let j = 0; j < n - 1; j++) {
    for (let i = 0; i < n - 1; i++) {
      const a = j * n + i, b = a + 1, c = a + n, d = c + 1;
      idx[o++] = a; idx[o++] = c; idx[o++] = b;
      idx[o++] = b; idx[o++] = c; idx[o++] = d;
    }
  }
  return new THREE.BufferAttribute(idx, 1);
}

let _indexCache = null;

/**
 * A leaf of the quadtree. Holds its own descriptor and, once the worker has
 * answered, its mesh. Nodes are cheap; meshes are not, so a node exists as soon
 * as the tree wants it and carries a mesh only while it is actually drawn.
 */
class Node {
  constructor(level, ix, iz, size, rootHalf) {
    this.level = level;
    this.ix = ix;
    this.iz = iz;
    this.size = size;
    this.x0 = -rootHalf + ix * size;
    this.z0 = -rootHalf + iz * size;
    this.cx = this.x0 + size * 0.5;
    this.cz = this.z0 + size * 0.5;
    this.id = `${level}/${ix}/${iz}`;
    this.children = null;
    this.mesh = null;
    this.requested = false;
    this.lastUsed = 0;
  }

  get ready() {
    return this.mesh !== null;
  }

  /** True once every descendant that will be drawn has geometry. */
  subtreeReady() {
    if (!this.children) return this.ready;
    for (const c of this.children) if (!c.subtreeReady()) return false;
    return true;
  }
}

export class QuadSphere {
  /**
   * @param field  a fully assembled TerrainField (frame set, pole set)
   * @param opts.extent    half-width of the root patch, metres
   * @param opts.leafSize  smallest leaf edge, metres — sets the finest detail
   */
  constructor(field, opts = {}) {
    this.field = field;
    this.profile = field.profile || biomeProfile(field.planet);
    this.object3d = new THREE.Group();

    // 160 km of ground either way, down to 40 m leaves. The root has to reach
    // past the true horizon (about 80 km on an Earth-sized world from head
    // height) or the terrain visibly stops short of where the sky should start.
    this.extent = opts.extent ?? 160000;
    this.leafSize = opts.leafSize ?? 40;
    this.maxLevel = Math.max(0, Math.round(Math.log2((this.extent * 2) / this.leafSize)));
    // How many node-widths from the camera a node splits. Higher is sharper and
    // costs quadratically more chunks.
    this.split = opts.split ?? 2.4;
    this.budget = opts.budget ?? 6;   // node requests in flight

    if (!_indexCache) _indexCache = buildIndex(RES + 2);
    this.index = _indexCache;

    this.root = new Node(0, 0, 0, this.extent * 2, this.extent);
    this.nodes = new Map([[this.root.id, this.root]]);
    this.pending = new Set();
    this.queue = [];
    this.frame = 0;
    this._workers = [];
    this._rr = 0;
    this._fallback = null;
    this._material = this._buildMaterial();
  }

  _buildMaterial() {
    const L = layerUniformArrays(this.profile);
    return new THREE.ShaderMaterial({
      uniforms: {
        uCamLocal: { value: new THREE.Vector3() },
        uRootSize: { value: this.extent * 2 },
        uSplit: { value: this.split },
        uLayerColor: { value: L.color.map((c) => new THREE.Color(c[0], c[1], c[2])) },
        uLayerEmissive: { value: L.emissive.map((c) => new THREE.Color(c[0], c[1], c[2])) },
        uRough: { value: new THREE.Vector4(...L.rough) },
        uFreeze: { value: this.profile.freeze },
        uBeachBand: { value: this.profile.beachBand },
        uSnowFactor: { value: 1 },
        uMaxElev: { value: this.profile.maxElev ?? 5000 },
        uSunDir: { value: new THREE.Vector3(0.4, 0.72, 0.56).normalize() },
        uSunColor: { value: new THREE.Color(1, 0.96, 0.9) },
        uSkyColor: { value: new THREE.Color(0.22, 0.3, 0.42) },
        uGroundColor: { value: new THREE.Color(0.06, 0.05, 0.045) },
        uUpLocal: { value: new THREE.Vector3(0, 1, 0) },
        uFogDensity: { value: 1 / 42000 },
        uFogColor: { value: new THREE.Color(0.5, 0.6, 0.72) },
      },
      vertexShader: TERRAIN_VERT,
      fragmentShader: TERRAIN_FRAG,
    });
  }

  get material() {
    return this._material;
  }

  /**
   * Spin up the worker pool and hand it the field.
   *
   * Module workers are still refused in a few places — `file://`, some embedded
   * webviews — and the harness needs to keep working there, so the worker module
   * doubles as a plain import. `terrain.worker.js` guards its own glue on
   * `WorkerGlobalScope`, so importing it on the main thread yields the same
   * `buildNode` with no worker side effects.
   */
  async init() {
    const payload = { type: 'init', field: this.field.serialize(), season: 0 };
    const count = Math.max(1, Math.min(4, (navigator.hardwareConcurrency || 4) - 1));

    try {
      const ready = [];
      for (let i = 0; i < count; i++) {
        const w = new Worker(new URL('./terrain.worker.js', import.meta.url), { type: 'module' });
        w.onmessage = (e) => this._onMessage(e.data);
        w.onerror = () => { /* handled by the fallback below */ };
        this._workers.push(w);
        ready.push(new Promise((res, rej) => {
          const t = setTimeout(() => rej(new Error('worker init timeout')), 8000);
          const prev = w.onmessage;
          w.onmessage = (e) => {
            if (e.data && e.data.type === 'ready') { clearTimeout(t); w.onmessage = prev; res(); }
            else prev(e);
          };
          w.postMessage(payload);
        }));
      }
      await Promise.all(ready);
    } catch (err) {
      for (const w of this._workers) w.terminate();
      this._workers = [];
      const mod = await import('./terrain.worker.js');
      this._fallback = { mod, ctx: mod.createContext(payload) };
      console.info('[QuadSphere] workers unavailable, generating inline:', err.message);
    }
    return this;
  }

  _onMessage(msg) {
    if (!msg || msg.type !== 'node') return;
    this.pending.delete(msg.id);
    const node = this.nodes.get(msg.id);
    if (!node) return;         // tree moved on while this was in flight
    this._attach(node, msg);
  }

  _attach(node, data) {
    const geo = new THREE.BufferGeometry();
    geo.setAttribute('position', new THREE.BufferAttribute(data.position, 3));
    geo.setAttribute('normal', new THREE.BufferAttribute(data.normal, 3));
    geo.setAttribute('aMorph', new THREE.BufferAttribute(data.morph, 4));
    geo.setAttribute('aTerra', new THREE.BufferAttribute(data.terra, 4));
    geo.setIndex(this.index);
    // The worker already knows the vertical span; computing it again here would
    // walk every vertex on the main thread for a number we were handed.
    geo.boundingSphere = new THREE.Sphere(
      new THREE.Vector3(0, (data.minY + data.maxY) * 0.5, 0),
      Math.hypot(node.size * 0.75, (data.maxY - data.minY) * 0.5 + 1),
    );

    const mesh = new THREE.Mesh(geo, this._material);
    mesh.position.set(data.ox, 0, data.oz);
    mesh.frustumCulled = true;
    mesh.visible = false;      // the traversal decides who is drawn
    node.mesh = mesh;
    node.minY = data.minY;
    node.maxY = data.maxY;
    this.object3d.add(mesh);
  }

  _request(node) {
    if (node.requested || this.pending.has(node.id)) return;
    node.requested = true;
    this.queue.push(node);
  }

  _pump() {
    // Nearest first: the chunk under the player matters more than one on the
    // horizon, and a distance sort is what stops a fast descent from filling
    // the queue with sky.
    if (!this.queue.length) return;
    this.queue.sort((a, b) => a._pri - b._pri);
    while (this.queue.length && this.pending.size < this.budget) {
      const node = this.queue.shift();
      if (!this.nodes.has(node.id)) { node.requested = false; continue; }
      const desc = {
        id: node.id, x0: node.x0, z0: node.z0,
        size: node.size, res: RES, level: node.level,
      };
      this.pending.add(node.id);
      if (this._fallback) {
        // Inline path: still asynchronous, so one enormous chunk cannot stall
        // the frame it was asked for.
        const { mod, ctx } = this._fallback;
        Promise.resolve().then(() => {
          try {
            this._onMessage({ ...mod.buildNode(ctx, desc), type: 'node' });
          } catch (err) {
            this.pending.delete(node.id);
            console.error('[QuadSphere] inline build failed', err);
          }
        });
      } else {
        this._workers[this._rr++ % this._workers.length].postMessage({ type: 'node', desc });
      }
    }
  }

  /**
   * Decide the cut of the tree for this camera position and draw it.
   * `camLocal` is in the local frame, the same space the nodes live in.
   */
  update(camLocal) {
    this.frame++;
    this._material.uniforms.uCamLocal.value.copy(camLocal);

    const draw = [];
    this._visit(this.root, camLocal, draw);

    // Hide everything, then show the chosen cut. Cheaper than diffing sets and
    // impossible to get wrong.
    for (const n of this.nodes.values()) if (n.mesh) n.mesh.visible = false;
    for (const n of draw) if (n.mesh) n.mesh.visible = true;

    this._pump();
    this._retire();
  }

  _visit(node, cam, draw) {
    node.lastUsed = this.frame;

    const dx = cam.x - node.cx;
    const dz = cam.z - node.cz;
    // Horizontal distance to the node's edge, not its centre: a node you are
    // standing on the corner of is zero away, and measuring to the centre makes
    // large nodes split far too late.
    const ex = Math.max(0, Math.abs(dx) - node.size * 0.5);
    const ez = Math.max(0, Math.abs(dz) - node.size * 0.5);
    const dist = Math.hypot(ex, ez, cam.y - (node.maxY ?? 0));
    node._pri = dist;

    const wantSplit = node.level < this.maxLevel && dist < node.size * this.split;

    if (!wantSplit) {
      this._request(node);
      draw.push(node);
      if (node.children) this._prune(node);
      return;
    }

    if (!node.children) {
      node.children = [];
      const h = node.size * 0.5;
      for (let j = 0; j < 2; j++) {
        for (let i = 0; i < 2; i++) {
          const c = new Node(node.level + 1, node.ix * 2 + i, node.iz * 2 + j, h, this.extent);
          this.nodes.set(c.id, c);
          node.children.push(c);
        }
      }
    }

    // Descend only when all four immediate children can stand in for this node.
    //
    // The first version asked whether the whole SUBTREE was ready, which sounds
    // like the safe version of the same idea and is not: on a twelve-level tree
    // the deepest leaf is never ready at the same moment as every one of its
    // nine hundred cousins, so the condition never fired, and the realm drew
    // its 240 km root node — one chunk, seven kilometres between vertices —
    // while four hundred and seventy-nine finished meshes sat in the scene
    // invisible. Ready-or-not has to be answered one level at a time, so the cut
    // descends as geometry arrives instead of waiting for a moment that never
    // comes.
    //
    // Either the node is drawn or all four children are; never both, so nothing
    // overlaps and there is nothing to z-fight.
    let childrenReady = true;
    for (const c of node.children) if (!c.ready) { childrenReady = false; break; }

    if (childrenReady) {
      for (const c of node.children) this._visit(c, cam, draw);
      return;
    }

    for (const c of node.children) {
      c.lastUsed = this.frame;
      c._pri = Math.hypot(cam.x - c.cx, cam.z - c.cz);
      this._request(c);
    }
    this._request(node);
    draw.push(node);
  }

  _prune(node) {
    if (!node.children) return;
    for (const c of node.children) {
      this._prune(c);
      this.nodes.delete(c.id);
      if (c.mesh) {
        this.object3d.remove(c.mesh);
        c.mesh.geometry.dispose();
      }
    }
    node.children = null;
  }

  /** Drop geometry for nodes the traversal has not wanted for a while. */
  _retire() {
    if (this.nodes.size < 900) return;
    for (const n of this.nodes.values()) {
      if (n.mesh && this.frame - n.lastUsed > 240) {
        this.object3d.remove(n.mesh);
        n.mesh.geometry.dispose();
        n.mesh = null;
        n.requested = false;
      }
    }
  }

  /** True once there is unbroken ground beneath the camera. */
  get settled() {
    return this.pending.size === 0 && this.queue.length === 0 && this.root.subtreeReady();
  }

  dispose() {
    for (const w of this._workers) w.terminate();
    this._workers = [];
    for (const n of this.nodes.values()) {
      if (n.mesh) n.mesh.geometry.dispose();
    }
    this.nodes.clear();
    this._material.dispose();
    this.object3d.clear();
  }
}
